### ISSUE TITLE
Icon Request [Hue Festavia]

### ISSUE THREAD

**Issue by yvansandoz** [arallsopp/hass-hue-icons#210] opened 2022-12-24 06:02 UTC
**What is the specific model of hue fixture/bulb that you want an icon for**

**[Provide a URL that points to an image of this fixture/bulb](https://www.philips-hue.com/en-us/p/hue-white-and-color-ambiance-festavia-string-lights/046677580148)**

**Additional context**

**Comment by arallsopp** [comment] 2022-12-24 09:55
Welcome @yvansandoz.

That link points to festavia string lights, if I'm seeing it correctly. These are already in the current release [v1.2.48] (https://github.com/arallsopp/hass-hue-icons/releases/tag/v1.2.48).

| Icon | Name | Keywords
| :--- | :--- | :--- |
| ![hue:festavia](https://raw.githubusercontent.com/arallsopp/hass-hue-icons/main/docs/custom_svgs/festavia.svg)| hue:festavia| light, christmas, string|

Please let me know if there's anything you need or I've misunderstood.

**Comment by arallsopp** [comment] 2022-12-24 10:05
marking for close as a duplicate of #209. Please feel free to re-open if there's something I've missed.

**Closed by arallsopp** 2022-12-24 10:05 UTC
Labels: duplicate, icon request

**Comment by yvansandoz** [comment] 2022-12-25 14:19
Sorry, I didn't see this option. In my head I was looking for a pine tree with lights on it. 
Take care,
Yvan
