### ISSUE TITLE
Backstepping in version?

### ISSUE THREAD

**Issue by WallyDW** [arallsopp/hass-hue-icons#155] opened 2022-05-05 08:28 UTC
Am I the only one having a upgrade notification in HA that tells me I have downloaded version 1.2.20 and available version is 1.2.19?

It is not really telling me what version I am running currently though. 

![billede](https://user-images.githubusercontent.com/86269202/166887546-d16ae120-2d3b-4114-a521-c4cc66673652.png)

**Comment by satyambaba** [comment] 2022-05-05 08:33
I am having the same issue after updating to HA 2022.5. The latest version I installed is v1.2.20, however github shows latest release as v1.2.19.

https://github.com/arallsopp/hass-hue-icons/releases

**Comment by arallsopp** [comment] 2022-05-05 08:34
Interesting. I don't see that, but its evidently a thing :)

Give me a few minutes to push [v.1.2.21](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.21) and we can see if that clears it?

**Comment by arallsopp** [comment] 2022-05-05 08:36
Actually, that's definitely a thing because I can't see release 20 anymore... Wonder where that went? Well, expect 21 will fix it.

**Comment by arallsopp** [comment] 2022-05-05 08:45
Thanks @WallyDW for raising, and @satyambaba for the clarificiation.

It looks like [v.1.2.20](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.20) has become a 'tag' rather than a release in the github system (though I'm not sure how that happens after the release is published). 

Anyway, [v.1.2.21](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.21) is up now, and that's definitely a release so hopefully it sticks.

Let me know if you still see the issue, or if its gone away?

**Comment by satyambaba** [comment] 2022-05-05 08:54
> Thanks @WallyDW for raising, and @satyambaba for the clarificiation.
> 
> It looks like [v.1.2.20](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.20) has become a 'tag' rather than a release in the github system (though I'm not sure how that happens after the release is published).
> 
> Anyway, [v.1.2.21](https://github.com/arallsopp/hass-hue-icons/releases/tag/v.1.2.21) is up now, and that's definitely a release so hopefully it sticks.
> 
> Let me know if you still see the issue, or if its gone away?

I can confirm, v1.2.21 solves the issue. I was able to successfully install v1.2.21.

**Comment by arallsopp** [comment] 2022-05-05 08:56
Excellent. @ludeeus suggested it might be a github issue (see the bottom of [this ticket](https://github.com/hacs/integration/issues/2656)) so I'll flag it to them lest its affecting others.

Closing for now.

**Closed by arallsopp** 2022-05-05 08:56 UTC
Labels: bug

**Comment by WallyDW** [comment] 2022-05-05 09:03
Now version 1.2.21 is available and installed perfectly.
Thanks!

**Comment by arallsopp** [comment] 2022-05-05 09:05
Thanks @WallyDW. Glad the issue is resolved. Incidentally, I followed ludeeus' suggestion and edited the release. For me, at least, github now shows it back in the [releases](https://github.com/arallsopp/hass-hue-icons/releases) list.
